### PR TITLE
HID-1817 - Upgrade google-libphonenumber

### PR DESCRIPTION
**Pull request by guillaumev**

### CODE REVIEW

**Comment by rupl** [comment]
I'm getting npm install errors when attempting to setup the PR, all related to the `@bower_components` namespaced packages. Am I missing something obvious?

some example logs:

```
32 silly fetchPackageMetaData error for @bower_components/angular-md5@github:gdi2290/angular-md5#~0.1.10 Command failed: git checkout ~0.1.10
32 silly fetchPackageMetaData error: pathspec '~0.1.10' did not match any file(s) known to git
33 silly fetchPackageMetaData error for @bower_components/angular-jwt@github:auth0/angular-jwt#^0.1.11 Command failed: git checkout ^0.1.11
33 silly fetchPackageMetaData error: pathspec '^0.1.11' did not match any file(s) known to git
34 silly fetchPackageMetaData error for @bower_components/angular-localforage@github:ocombe/angular-localForage#~1.3.3 Command failed: git checkout ~1.3.3
34 silly fetchPackageMetaData error: pathspec '~1.3.3' did not match any file(s) known to git
35 silly fetchPackageMetaData error for @bower_components/angular-google-gapi@github:maximepvrt/angular-google-gapi#^1.0.1 Command failed: git checkout ^1.0.1
35 silly fetchPackageMetaData error: pathspec '^1.0.1' did not match any file(s) known to git
36 silly fetchPackageMetaData error for @bower_components/angular-clipboard@github:omichelsen/angular-clipboard#^1.6.2 Command failed: git checkout ^1.6.2
36 silly fetchPackageMetaData error: pathspec '^1.6.2' did not match any file(s) known to git
37 silly fetchPackageMetaData error for @bower_components/angular-gettext@github:rubenv/angular-gettext#^2.4.1 Command failed: git checkout ^2.4.1
37 silly fetchPackageMetaData error: pathspec '^2.4.1' did not match any file(s) known to git
```

**Comment by guillaumev** [comment]
@rupl Try with yarn (yarn --ignore-engines) maybe...

**Comment by rupl** [comment]
perfect, of course. I forgot that yarn is the primary package manager for this project.

So, once the upgrade was compiled, the client-side allowed the phone number to be submitted, but I am now seeing errors when saving a new number:

> User validation failed: phone_numbers.1.number: +263 73 XXX XXXX is not a valid phone number !

This is the same phone number that prompted this upgrade.

I suppose for this specific PR we're done, but we probably need to do something on the API side.

**Review by rupl — APPROVED** [review]

**Comment by rupl** [comment]
I totally forgot about this PR. The dependent API PR has long been in dev. I'll merge this.

**Pull request merged**
